<<<<<<< HEAD
<<<<<<< HEAD
spring:
  mail:
    host: smtp.gmail.com
    port: 8888
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
=======
spring:
  mail:
    host: smtp.gmail.com
    port: 8888
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
>>>>>>> refs/remotes/origin/킹줴지우지
=======
spring:
  mail:
    host: smtp.gmail.com
    port: 8888
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
>>>>>>> refs/remotes/origin/승범
      auth-code-expiration-millis: 300000  # 5 * 60 * 1000(밀리초) == 5분